### ISSUE TITLE
The implementation of ballistics

### ISSUE THREAD

**Issue by ThyrixYang** [BensonRen/BDIMNNA#1]
Hi,

I found that the ballistics is implemented as (line127 in generate_ballistics.py)

```
 output[:, 1] = x2 - m / k / k * ((g*m + v2 * k) * exponential_part + g*t*k)
```
However, the formula in the original paper (Benchmarking Invertible Architectures on Inverse Problems) suggests
```
 output[:, 1] = x2 - m / k / k * (g*m + (v2 * k) * exponential_part + g*t*k)
```

Is this a bug?

**Comment by ThyrixYang** [comment]
It seems that the formula in that paper is wrong, but I'm not sure whether this implementation is correct. Have you checked this formula?

---
Edit: I found that the formula in your supplementary is also wrong.

**Comment by BensonRen** [comment]
Dear Yang,

Thank you so much for your detailed analysis of our paper and code.

I also noticed that on the original paper there was a typo where "(g*m + v2*k)*exponential" is written into "g*m + (v2*k)*exponential". Since their implementation is alright, I did not bother them about that small typo.

I can confirm that the version in my code generate_ballistics.py is the correct implementation, the (g*m + v2*k)*exponential one. If you do solve the second-order ordinary differential equation, you would see that is the case. (I believe you already plugged in t=0 and found the original implementation is incorrect)

However, during the last-minute writing, as we totally cited their benchmark problem, I accidentally copied the equation from the Kruse paper with the typo in it. I am very sorry for the confusion caused and would update our supplementary on arxiv.
